[project]
name = "project-1-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "neo4j>=6.0.3",
    "openai>=2.8.1",
    "typer>=0.20.0",
]
